name: todo_app
description: "A lightweight and efficient To-Do List app built with Flutter."

publish_to: 'none' # This line prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.0+4
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add any assets or custom fonts here if needed in the future.
  # assets:
  #   - images/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
